services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - AUTH_SERVER_URL=http://auth-server:8080/realms/test
      - AUTH_HOST=http://localhost:8080
    depends_on:
      - auth-server
  auth-server:
    image: keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_PROXY_HEADERS=forwarded
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
      - ./keycloak/startup.sh:/opt/keycloak/bin/startup.sh
    entrypoint: [""]
    command: ["/bin/bash", "-c", "/opt/keycloak/bin/startup.sh"]
