services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - AUTH_ENDPOINT=http://localhost:9000/realms/master
    env_file:
      - .env
  auth:
    image: keycloak/keycloak:latest
    ports:
      - "9000:9000"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev --http-port 9000
